---
steps:

  - name: ':package: Build and Package'
    command: './package.sh'
    env:
      AWS_REGION: ap-southeast-2
    agents:
      os: 'linux'
    artifact_paths: '*.zip'

  - wait

  - name: ':shipit: Ship to s3'
    command: 'cd deploy && bundle install && rake upload'
    env:
      AWS_REGION: ap-southeast-2
      ENVIRONMENT: kaos
    agents:
      os: 'linux'

  - wait

  - name: ':shipit: Deploy to kaos (東京)'
    command: 'cd deploy && ./deploy.sh'
    env:
      AWS_REGION: ap-southeast-2
      ENVIRONMENT: kaos
    agents:
      os: 'linux'
