env:
  AWS_REGION: ap-southeast-2
  DEFAULT_AWS_REGION: ap-southeast-2

steps:
  - name: ':nodejs: Test & Deploy'
    command: 'docker run -t -v $PWD:/tmp -w /tmp node:4 /bin/bash ./deploy.sh'
    agents:
      os: 'linux'
    concurrency: 1
    concurrency_group: "${BUILDKITE_PIPELINE_SLUG}/deploy-${BUILDKITE_BRANCH}-to-kaos"
