require 'cloudformer'
require_relative 'assume_role.rb'
require 'aws-sdk'

AssumeRole.new.set_credentials!

environment = ENV['ENVIRONMENT']
version = "1.#{ENV['BUILDKITE_BUILD_NUMBER']}"

Cloudformer::Tasks.new("hammertime") do |t|
  t.template = "hammertime-cf.json"
  t.tags = []
  t.parameters = { "LambdaVersion" => version }
  t.capabilities = %w(CAPABILITY_IAM)
end

task :upload do
  sh 'rm -f *.zip && buildkite-agent artifact download "*.zip" ./' # && aws s3 cp stop-hammertime-*.zip s3://nib-kaos-lambdas/ && aws s3 cp start-hammertime-*.zip s3://nib-kaos-lambdas/'
  file_name = Dir.glob("*.zip").first
  bucket_name = 'nib-kaos-lambdas'
  s3 = AWS::S3.new
  key = File.basename(file_name)
  s3.buckets[bucket_name].objects[key].write(:file => file_name)
  puts "Uploading file #{file_name} to bucket #{bucket_name}."
end
