require 'cloudformer'
require_relative 'assume_role.rb'

AssumeRole.new.set_credentials!

environment = ENV['ENVIRONMENT']

Cloudformer::Tasks.new("hammertime") do |t|
  t.template = "hammertime-cf.json"
  t.parameters = {}
  t.capabilities = %w(CAPABILITY_IAM)
end
